In [1]:
import os
import pandas as pd

PROC_DIR = "../data/processed"
IN_PATH = os.path.join(PROC_DIR, "darko_with_minutes_2025_26.csv")

df = pd.read_csv(IN_PATH)
df.shape, df.columns

((548, 31),
 Index(['nba_id', 'team', 'player_name', 'Experience', 'impact_dpm',
        'DPM Improvement', 'O-DPM', 'D-DPM', 'Box DPM', 'Box O-DPM',
        'Box D-DPM', 'FGA/100', 'FG2%', 'FG3A/100', 'FG3%', 'FG3ARate%',
        'RimFGA/100', 'RimFG%', 'FTA/100', 'FT%', 'FTARate%', 'USG%', 'REB/100',
        'AST/100', 'AST%', 'BLK/100', 'BLK%', 'STL/100', 'STL%', 'TOV/100',
        'minutes'],
       dtype='object'))

In [2]:
replacement_dpm = df["impact_dpm"].quantile(0.20)
replacement_dpm

np.float64(-1.98000001907349)

In [3]:
df["VAR"] = df["impact_dpm"] - replacement_dpm
df[["player_name","team","impact_dpm","VAR","minutes"]].head()

               player_name                   team  impact_dpm   VAR  minutes
0             Nikola Jokic         Denver Nuggets        6.71  8.69   1237.0
1            Kawhi Leonard   Los Angeles Clippers        6.20  8.18   1211.0
2  Shai Gilgeous-Alexander  Oklahoma City Thunder        6.06  8.04   1632.0
3    Giannis Antetokounmpo        Milwaukee Bucks        6.01  7.99    876.0
4         Donovan Mitchell    Cleveland Cavaliers        5.42  7.40   1622.0

In [4]:
df["VAR"].describe()

count    548.000000
mean       1.372226
std        1.685307
min       -2.880000
25%        0.140000
50%        1.110000
75%        2.310000
max        8.690000
Name: VAR, dtype: float64

In [5]:
df.sort_values("VAR", ascending=False)[["player_name","team","impact_dpm","VAR","minutes"]].head(15)

                player_name                    team  impact_dpm   VAR  minutes
0              Nikola Jokic          Denver Nuggets        6.71  8.69   1237.0
1             Kawhi Leonard    Los Angeles Clippers        6.20  8.18   1211.0
2   Shai Gilgeous-Alexander   Oklahoma City Thunder        6.06  8.04   1632.0
3     Giannis Antetokounmpo         Milwaukee Bucks        6.01  7.99    876.0
4          Donovan Mitchell     Cleveland Cavaliers        5.42  7.40   1622.0
5         Victor Wembanyama       San Antonio Spurs        5.16  7.14   1041.0
6              Jayson Tatum          Boston Celtics        5.03  7.01      0.0
7           Anthony Edwards  Minnesota Timberwolves        4.76  6.74   1489.0
8               Luka Doncic      Los Angeles Lakers        4.21  6.19   1476.0
9             Chet Holmgren   Oklahoma City Thunder        3.83  5.81   1316.0
10        Tyrese Haliburton          Indiana Pacers        3.65  5.63      0.0
11              Joel Embiid      Philadelphia 76ers        3.37  5.35    900.0
12              Rudy Gobert  Minnesota Timberwolves        3.07  5.05   1566.0
13             Aaron Gordon          Denver Nuggets        3.04  5.02    642.0
14             James Harden    Los Angeles Clippers        3.00  4.98   1559.0

In [6]:
OUT_PATH = os.path.join(PROC_DIR, "player_var_2025_26.csv")
df.to_csv(OUT_PATH, index=False)
print("Saved:", OUT_PATH)

Saved: ../data/processed/player_var_2025_26.csv